package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/mrabhi2k3/telegofer/tl/parser"
)

// Generator produces Go source code from a parsed TL Schema.
type Generator struct {
	pkgName string
}

// New creates a code generator that targets the specified Go package.
func New(pkgName string) *Generator {
	return &Generator{pkgName: pkgName}
}

// Generate produces formatted Go source code representing all types,
// constructors, and functions in the provided schema.
func (g *Generator) Generate(schema *parser.Schema) ([]byte, error) {
	var buf bytes.Buffer

	// File header
	buf.WriteString("// Code generated by teleGofer TL generator. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", g.pkgName)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"github.com/mrabhi2k3/telegofer/tl/decoder\"\n")
	buf.WriteString("\t\"github.com/mrabhi2k3/telegofer/tl/encoder\"\n")
	buf.WriteString(")\n\n")

	// 1. Group constructors by ResultType to generate interfaces for polymorphic sum types (> 1 constructor)
	typesMap := make(map[string][]parser.Definition)
	for _, c := range schema.Constructors {
		typesMap[c.ResultType] = append(typesMap[c.ResultType], c)
	}

	for typeName, constructors := range typesMap {
		if isPrimitiveType(typeName) || typeName == "Bool" || typeName == "True" {
			continue
		}
		// Single constructor types are concrete structs; no interface needed
		if len(constructors) <= 1 {
			continue
		}

		interfaceName := getInterfaceName(typeName, constructors)

		fmt.Fprintf(&buf, "// %s represents the polymorphic TL sum type for %s.\n", interfaceName, typeName)
		fmt.Fprintf(&buf, "type %s interface {\n", interfaceName)
		buf.WriteString("\tTLID() uint32\n")
		buf.WriteString("\tEncode(e *encoder.Encoder) error\n")
		buf.WriteString("\tDecode(d *decoder.Decoder) error\n")
		fmt.Fprintf(&buf, "\tis%s()\n", interfaceName)
		buf.WriteString("}\n\n")

		// Decode helper: Decode<Type>(d *decoder.Decoder) (<InterfaceName>, error)
		fmt.Fprintf(&buf, "// Decode%s reads a boxed %s constructor from the decoder.\n", interfaceName, interfaceName)
		fmt.Fprintf(&buf, "func Decode%s(d *decoder.Decoder) (%s, error) {\n", interfaceName, interfaceName)
		buf.WriteString("\tcrc, err := d.PeekUint()\n")
		buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		buf.WriteString("\tswitch crc {\n")
		for _, c := range constructors {
			structName := getStructName(c)
			fmt.Fprintf(&buf, "\tcase 0x%08x:\n", c.ID)
			fmt.Fprintf(&buf, "\t\tv := &%s{}\n", structName)
			buf.WriteString("\t\tif err := v.Decode(d); err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
			buf.WriteString("\t\treturn v, nil\n")
		}
		buf.WriteString("\tdefault:\n")
		fmt.Fprintf(&buf, "\t\treturn nil, fmt.Errorf(\"unknown constructor 0x%%08x for %s\", crc)\n", interfaceName)
		buf.WriteString("\t}\n}\n\n")
	}

	// 2. Generate concrete structs for all constructors
	for _, c := range schema.Constructors {
		if err := g.generateStruct(&buf, c, false, typesMap); err != nil {
			return nil, err
		}
	}

	// 3. Generate concrete structs for all functions
	for _, fn := range schema.Functions {
		if err := g.generateStruct(&buf, fn, true, typesMap); err != nil {
			return nil, err
		}
	}

	src := buf.Bytes()
	formatted, err := format.Source(src)
	if err != nil {
		return src, fmt.Errorf("gofmt error: %w\nSource:\n%s", err, string(src))
	}

	return formatted, nil
}

func (g *Generator) generateStruct(buf *bytes.Buffer, def parser.Definition, isFn bool, typesMap map[string][]parser.Definition) error {
	structName := getStructName(def)

	fmt.Fprintf(buf, "// %s represents the TL %s `%s#%08x`.\n", structName, map[bool]string{true: "function", false: "constructor"}[isFn], def.Name, def.ID)
	fmt.Fprintf(buf, "type %s struct {\n", structName)

	hasFlags := false
	flagField := ""

	for _, p := range def.Params {
		if p.Type == "#" {
			hasFlags = true
			flagField = toGoPublicName(p.Name)
			fmt.Fprintf(buf, "\t%s uint32\n", flagField)
			continue
		}
		fieldName := toGoPublicName(p.Name)
		goType := toGoType(p, typesMap)
		fmt.Fprintf(buf, "\t%s %s\n", fieldName, goType)
	}

	buf.WriteString("}\n\n")

	// TLID()
	fmt.Fprintf(buf, "func (v *%s) TLID() uint32 { return 0x%08x }\n\n", structName, def.ID)

	// Marker interface method if belonging to a polymorphic interface
	if !isFn {
		if ctors, ok := typesMap[def.ResultType]; ok && len(ctors) > 1 {
			interfaceName := getInterfaceName(def.ResultType, ctors)
			fmt.Fprintf(buf, "func (v *%s) is%s() {}\n\n", structName, interfaceName)
		}
	}

	// Encode()
	fmt.Fprintf(buf, "func (v *%s) Encode(e *encoder.Encoder) error {\n", structName)
	fmt.Fprintf(buf, "\te.PutUint(0x%08x)\n", def.ID)

	// Pre-calculate flags bitmask if flags exist
	if hasFlags {
		for _, p := range def.Params {
			if p.Flag != nil {
				fieldName := toGoPublicName(p.Name)
				if p.Flag.IsTrue {
					fmt.Fprintf(buf, "\tif v.%s {\n\t\tv.%s |= (1 << %d)\n\t}\n", fieldName, flagField, p.Flag.Bit)
				} else {
					if isPointerType(p) {
						fmt.Fprintf(buf, "\tif v.%s != nil {\n\t\tv.%s |= (1 << %d)\n\t}\n", fieldName, flagField, p.Flag.Bit)
					} else if p.Type == "string" || p.Type == "bytes" || p.IsVector {
						fmt.Fprintf(buf, "\tif len(v.%s) > 0 {\n\t\tv.%s |= (1 << %d)\n\t}\n", fieldName, flagField, p.Flag.Bit)
					}
				}
			}
		}
	}

	// Encode fields in order
	for _, p := range def.Params {
		fieldName := toGoPublicName(p.Name)
		if p.Type == "#" {
			fmt.Fprintf(buf, "\te.PutUint(v.%s)\n", fieldName)
			continue
		}

		if p.Flag != nil {
			if p.Flag.IsTrue {
				// True is encoded by bit presence only; no payload on wire
				continue
			}
			fmt.Fprintf(buf, "\tif (v.%s & (1 << %d)) != 0 {\n", flagField, p.Flag.Bit)
			writeEncodeField(buf, p, "v."+fieldName, "\t\t")
			buf.WriteString("\t}\n")
		} else {
			writeEncodeField(buf, p, "v."+fieldName, "\t")
		}
	}

	buf.WriteString("\treturn nil\n}\n\n")

	// Decode()
	fmt.Fprintf(buf, "func (v *%s) Decode(d *decoder.Decoder) error {\n", structName)
	buf.WriteString("\tcrc, err := d.Uint()\n\tif err != nil {\n\t\treturn err\n\t}\n")
	fmt.Fprintf(buf, "\tif crc != 0x%08x {\n\t\treturn fmt.Errorf(\"mismatched constructor: expected 0x%08x, got 0x%%08x\", crc)\n\t}\n", def.ID, def.ID)

	for _, p := range def.Params {
		fieldName := toGoPublicName(p.Name)
		if p.Type == "#" {
			fmt.Fprintf(buf, "\tif v.%s, err = d.Uint(); err != nil {\n\t\treturn err\n\t}\n", fieldName)
			continue
		}

		if p.Flag != nil {
			if p.Flag.IsTrue {
				fmt.Fprintf(buf, "\tv.%s = (v.%s & (1 << %d)) != 0\n", fieldName, flagField, p.Flag.Bit)
				continue
			}
			fmt.Fprintf(buf, "\tif (v.%s & (1 << %d)) != 0 {\n", flagField, p.Flag.Bit)
			writeDecodeField(buf, p, "v."+fieldName, "\t\t", typesMap)
			buf.WriteString("\t}\n")
		} else {
			writeDecodeField(buf, p, "v."+fieldName, "\t", typesMap)
		}
	}

	buf.WriteString("\treturn nil\n}\n\n")

	return nil
}

func writeEncodeField(buf *bytes.Buffer, p parser.Param, access string, indent string) {
	switch p.Type {
	case "int":
		fmt.Fprintf(buf, "%se.PutInt(%s)\n", indent, access)
	case "long":
		fmt.Fprintf(buf, "%se.PutLong(%s)\n", indent, access)
	case "double":
		fmt.Fprintf(buf, "%se.PutDouble(%s)\n", indent, access)
	case "string":
		fmt.Fprintf(buf, "%se.PutString(%s)\n", indent, access)
	case "bytes":
		fmt.Fprintf(buf, "%se.PutBytes(%s)\n", indent, access)
	case "Bool":
		fmt.Fprintf(buf, "%se.PutBool(%s)\n", indent, access)
	case "int128":
		fmt.Fprintf(buf, "%se.PutInt128(%s)\n", indent, access)
	case "int256":
		fmt.Fprintf(buf, "%se.PutInt256(%s)\n", indent, access)
	default:
		if p.IsVector {
			fmt.Fprintf(buf, "%se.PutVectorHeader(len(%s))\n", indent, access)
			fmt.Fprintf(buf, "%sfor _, item := range %s {\n", indent, access)
			if isPrimitiveType(p.ElemType) {
				writeEncodePrimitive(buf, p.ElemType, "item", indent+"\t")
			} else {
				fmt.Fprintf(buf, "%s\tif err := item.Encode(e); err != nil {\n%s\t\treturn err\n%s\t}\n", indent, indent, indent)
			}
			fmt.Fprintf(buf, "%s}\n", indent)
		} else {
			fmt.Fprintf(buf, "%sif err := %s.Encode(e); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
		}
	}
}

func writeEncodePrimitive(buf *bytes.Buffer, typ string, access string, indent string) {
	switch typ {
	case "int":
		fmt.Fprintf(buf, "%se.PutInt(%s)\n", indent, access)
	case "long":
		fmt.Fprintf(buf, "%se.PutLong(%s)\n", indent, access)
	case "string":
		fmt.Fprintf(buf, "%se.PutString(%s)\n", indent, access)
	case "bytes":
		fmt.Fprintf(buf, "%se.PutBytes(%s)\n", indent, access)
	}
}

func writeDecodeField(buf *bytes.Buffer, p parser.Param, access string, indent string, typesMap map[string][]parser.Definition) {
	switch p.Type {
	case "int":
		fmt.Fprintf(buf, "%sif %s, err = d.Int(); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
	case "long":
		fmt.Fprintf(buf, "%sif %s, err = d.Long(); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
	case "double":
		fmt.Fprintf(buf, "%sif %s, err = d.Double(); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
	case "string":
		fmt.Fprintf(buf, "%sif %s, err = d.String(); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
	case "bytes":
		fmt.Fprintf(buf, "%sif %s, err = d.Bytes(); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
	case "Bool":
		fmt.Fprintf(buf, "%sif %s, err = d.Bool(); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
	case "int128":
		fmt.Fprintf(buf, "%sif %s, err = d.Int128(); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
	case "int256":
		fmt.Fprintf(buf, "%sif %s, err = d.Int256(); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
	default:
		if p.IsVector {
			fmt.Fprintf(buf, "%svecLen, err := d.VectorHeader()\n%sif err != nil {\n%s\treturn err\n%s}\n", indent, indent, indent, indent)
			elemType := toGoSingleType(p.ElemType, typesMap)
			fmt.Fprintf(buf, "%s%s = make([]%s, vecLen)\n", indent, access, elemType)
			fmt.Fprintf(buf, "%sfor i := 0; i < vecLen; i++ {\n", indent)
			if isPrimitiveType(p.ElemType) {
				writeDecodePrimitive(buf, p.ElemType, fmt.Sprintf("%s[i]", access), indent+"\t")
			} else {
				if isPolymorphic(p.ElemType, typesMap) {
					ifaceName := getInterfaceName(p.ElemType, typesMap[p.ElemType])
					fmt.Fprintf(buf, "%s\titem, err := Decode%s(d)\n%s\tif err != nil {\n%s\t\treturn err\n%s\t}\n%s\t%s[i] = item\n", indent, ifaceName, indent, indent, indent, indent, access)
				} else {
					fmt.Fprintf(buf, "%s\tif err := %s[i].Decode(d); err != nil {\n%s\t\treturn err\n%s\t}\n", indent, access, indent, indent)
				}
			}
			fmt.Fprintf(buf, "%s}\n", indent)
		} else {
			if isPolymorphic(p.Type, typesMap) {
				ifaceName := getInterfaceName(p.Type, typesMap[p.Type])
				fmt.Fprintf(buf, "%sitem, err := Decode%s(d)\n%sif err != nil {\n%s\treturn err\n%s}\n%s%s = item\n", indent, ifaceName, indent, indent, indent, indent, access)
			} else {
				fmt.Fprintf(buf, "%sif err := %s.Decode(d); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
			}
		}
	}
}

func writeDecodePrimitive(buf *bytes.Buffer, typ string, access string, indent string) {
	switch typ {
	case "int":
		fmt.Fprintf(buf, "%sif %s, err = d.Int(); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
	case "long":
		fmt.Fprintf(buf, "%sif %s, err = d.Long(); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
	case "string":
		fmt.Fprintf(buf, "%sif %s, err = d.String(); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
	case "bytes":
		fmt.Fprintf(buf, "%sif %s, err = d.Bytes(); err != nil {\n%s\treturn err\n%s}\n", indent, access, indent, indent)
	}
}

func toGoType(p parser.Param, typesMap map[string][]parser.Definition) string {
	if p.Flag != nil && p.Flag.IsTrue {
		return "bool"
	}
	if p.IsVector {
		return "[]" + toGoSingleType(p.ElemType, typesMap)
	}
	return toGoSingleType(p.Type, typesMap)
}

func toGoSingleType(t string, typesMap map[string][]parser.Definition) string {
	switch t {
	case "int":
		return "int32"
	case "long":
		return "int64"
	case "double":
		return "float64"
	case "string":
		return "string"
	case "bytes":
		return "[]byte"
	case "Bool":
		return "bool"
	case "int128":
		return "[16]byte"
	case "int256":
		return "[32]byte"
	default:
		if ctors, ok := typesMap[t]; ok && len(ctors) > 1 {
			return getInterfaceName(t, ctors)
		}
		return toGoPublicName(t)
	}
}

func isPolymorphic(typeName string, typesMap map[string][]parser.Definition) bool {
	if ctors, ok := typesMap[typeName]; ok {
		return len(ctors) > 1
	}
	return false
}

func getInterfaceName(typeName string, constructors []parser.Definition) string {
	baseName := toGoPublicName(typeName)
	// If any constructor has the exact same name as baseName, suffix the interface with "Class"
	for _, c := range constructors {
		if toGoPublicName(c.Name) == baseName {
			return baseName + "Class"
		}
	}
	return baseName
}

func getStructName(def parser.Definition) string {
	return toGoPublicName(def.Name)
}

func isPrimitiveType(t string) bool {
	switch t {
	case "int", "long", "double", "string", "bytes", "int128", "int256":
		return true
	default:
		return false
	}
}

func isPointerType(p parser.Param) bool {
	return !isPrimitiveType(p.Type) && !p.IsVector && p.Type != "Bool" && p.Type != "string" && p.Type != "bytes"
}

func toGoPublicName(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '.' || r == '_'
	})
	var out strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			out.WriteString(strings.ToUpper(p[:1]))
			out.WriteString(p[1:])
		}
	}
	return out.String()
}
